# Generated by Django 3.1.3 on 2021-01-24 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_contact'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='contact',
        ),
    ]
